name: Test auth
on:
  push:
    branches:
      - '*'

jobs:
  test_auth:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - name: Dump env
      run: env

    - name: Actions token url
      shell: bash
      run: echo ${ACTIONS_ID_TOKEN_REQUEST_URL}

    - name: Actions token id-token
      shell: bash
      run: echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/526897014808/locations/global/workloadIdentityPools/galaxy-tests-identity-pool/providers/gxy-tests-provider'
        service_account: 'galaxy-tests-repo-actions-sa@anvil-and-terra-development.iam.gserviceaccount.com'

    - name: Dump json
      run: 'cat /home/runner/work/galaxy-tests/galaxy-tests/*.json'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'gcloud info'
      run: 'gcloud info'

    - name: 'gcloud auth list'
      run: 'gcloud auth list'

    - name: 'List GKE clusters'
      run: 'gcloud container clusters list'
